# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=5, max_digits=50)),
                ('change', models.DecimalField(decimal_places=5, max_digits=50)),
                ('change_perc', models.DecimalField(decimal_places=5, max_digits=50)),
                ('market_cap', models.DecimalField(decimal_places=5, max_digits=50)),
                ('volume', models.DecimalField(decimal_places=5, max_digits=50)),
                ('last_update', models.DecimalField(decimal_places=5, max_digits=50)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yahoo_finance.Company')),
            ],
        ),
    ]
